import {
  ReferenceManifestSchema,
  type Category,
  type ReferenceEntry,
} from './reference-schema';

type Profile = {
  composition: string;
  typography?: string;
  palette: string;
  texture: string;
  hierarchy?: string;
  spacing?: string;
  motion: string;
  preserve: string;
  avoid: string;
};

type Seed = Omit<ReferenceEntry, 'brief' | 'imagePrompt' | 'filters'> & {
  extraFilters?: Category[];
  profile: Profile;
};

const categoryDefaults: Record<
  Category,
  Pick<Profile, 'typography' | 'hierarchy' | 'spacing'>
> = {
  'Print-Tech Paper': {
    typography: 'an editorial serif paired with compact utilitarian mono labels',
    hierarchy: 'a publication-like headline leads, followed by strict technical metadata',
    spacing: 'use a measured column grid with visible rules and generous headline breathing room',
  },
  'Dither Mono': {
    typography: 'stark serif or grotesk display type with small monospace controls',
    hierarchy: 'one high-contrast image or statement dominates a restrained interface',
    spacing: 'keep the frame sparse, aligned, and deliberately severe',
  },
  'Vast Quiet Cinematic': {
    typography: 'quiet display typography with compact, nearly invisible navigation',
    hierarchy: 'a full-bleed scene carries the experience while copy remains secondary',
    spacing: 'allow large uninterrupted fields and wide cinematic margins',
  },
  'Data-as-Texture': {
    typography: 'precise grotesk headlines with dense monospace or ASCII microcopy',
    hierarchy: 'a readable headline anchors a field of subordinate information',
    spacing: 'combine rigid grid alignment with intentionally dense data regions',
  },
  'Classical Remix': {
    typography: 'high-contrast classical serif type balanced by minimal modern controls',
    hierarchy: 'historic imagery and a monumental headline share the focal plane',
    spacing: 'use formal symmetry or museum-like margins with selective asymmetry',
  },
  'Glitched Antiquity': {
    typography: 'editorial serif forms interrupted by coded, pixel, or scan-line accents',
    hierarchy: 'an archival figure remains recognizable beneath controlled digital disruption',
    spacing: 'preserve a formal base grid while allowing localized visual rupture',
  },
  'Illustrated Storybook': {
    typography: 'friendly characterful display type paired with plain, legible interface copy',
    hierarchy: 'illustration establishes the world, then a concise action completes the story',
    spacing: 'use open scenic space with clearly grouped controls and soft visual rhythm',
  },
  'Reference Styles': {
    typography: 'a disciplined brand type system with clear display, body, and utility roles',
    hierarchy: 'make the product proposition immediately legible before supporting proof',
    spacing: 'use a consistent responsive grid and repeatable component rhythm',
  },
};

const buildEntry = (seed: Seed): ReferenceEntry => {
  const defaults = categoryDefaults[seed.primaryCategory];
  const profile = {
    ...defaults,
    ...seed.profile,
  };
  const filters = Array.from(
    new Set([seed.primaryCategory, ...(seed.extraFilters ?? [])]),
  );
  const brief = [
    `Composition: ${profile.composition}`,
    `Typography: ${profile.typography}`,
    `Palette: ${profile.palette}`,
    `Texture: ${profile.texture}`,
    `Hierarchy: ${profile.hierarchy}`,
    `Spacing: ${profile.spacing}`,
    `Motion: ${profile.motion}`,
    `Preserve: ${profile.preserve}`,
    `Avoid: ${profile.avoid}`,
  ].join('\n');
  const imagePrompt = [
    `Create a 16:10 website hero concept titled “${seed.title}”.`,
    profile.composition,
    `Use ${profile.typography}.`,
    `Palette: ${profile.palette}.`,
    `Surface treatment: ${profile.texture}.`,
    `Hierarchy: ${profile.hierarchy}.`,
    `Preserve ${profile.preserve}; avoid ${profile.avoid}.`,
    'Use original placeholder copy and original imagery; do not reproduce logos or branded assets from the reference.',
  ].join(' ');

  const { extraFilters: _extraFilters, profile: _profile, ...entry } = seed;
  return { ...entry, filters, brief, imagePrompt };
};

const imageFile = (number: number, extension: 'jpg' | 'png') =>
  `/assets/originals/${number}.${extension}`;

const imageSeeds: Seed[] = [
  {
    id: 'image-astra-italy', order: 1, title: 'Astra — Italy Travel System',
    styleDescriptor: 'Long-form editorial / modular itinerary',
    description: 'A complete travel landing page arranged like a compact magazine: monochrome collage, itinerary modules, proof points, price cards, and a dark conversion footer.',
    primaryCategory: 'Print-Tech Paper', extraFilters: ['Reference Styles'],
    tags: ['editorial grid', 'paper white', 'photo collage', 'condensed labels', 'modular cards', 'black footer'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'astra-travel', originalAsset: imageFile(1, 'jpg') },
    media: { poster: '/assets/posters/image-01.jpg', detailImage: imageFile(1, 'jpg'), original: imageFile(1, 'jpg') },
    quality: { tier: 'canonical', width: 4096, height: 3796, confidence: 0.96, reliableFor: ['layout', 'typography', 'component rhythm', 'palette'], note: 'High-resolution supplied composite; poster uses the upper hero while the full page remains available in detail view.' },
    profile: { composition: 'Build a tall editorial system from a centered black-and-white hero collage followed by alternating evidence, itinerary, and pricing modules.', palette: 'warm paper white, ink black, and restrained grey', texture: 'subtle paper grain, halftone photography, thin black rules', motion: 'mostly static; use only quiet image reveals and small hover inversions', preserve: 'the publication rhythm, modular storytelling, and disciplined two-color system', avoid: 'generic SaaS gradients, floating glass cards, oversized rounded corners' },
  },
  {
    id: 'image-dark-portal', order: 2, title: 'Nocturne Login Portal',
    styleDescriptor: 'Split-screen authentication / noir dither',
    description: 'A severe login screen pairs a dense dark form with a grainy lone figure, using a split composition to turn a utility flow into an atmospheric threshold.',
    primaryCategory: 'Dither Mono', extraFilters: ['Glitched Antiquity'],
    tags: ['split screen', 'dither photo', 'dark UI', 'utility form', 'grain', 'high contrast'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'welcome-portals', originalAsset: imageFile(2, 'png') },
    media: { poster: '/assets/posters/image-02.jpg', detailImage: imageFile(2, 'png'), original: imageFile(2, 'png') },
    quality: { tier: 'canonical', width: 2880, height: 2048, confidence: 0.98, reliableFor: ['layout', 'contrast', 'form styling', 'image treatment'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Divide the viewport into a compact authentication panel and an equally weighted cinematic portrait panel.', palette: 'charcoal, soft black, fog grey, and white', texture: 'coarse monochrome dithering and low-light film grain', motion: 'slow grain drift or a barely perceptible image zoom; keep the form still', preserve: 'the tense split, restrained controls, and cinematic figure', avoid: 'color accents, decorative icons, cheerful onboarding language' },
  },
  {
    id: 'image-light-portal', order: 3, title: 'Daylight Login Portal',
    styleDescriptor: 'Split-screen authentication / quiet monochrome',
    description: 'The companion authentication state uses a paper-white form beside a blurred meditative figure, showing how the same grid can shift from ominous to contemplative.',
    primaryCategory: 'Dither Mono', extraFilters: ['Vast Quiet Cinematic'],
    tags: ['split screen', 'soft monochrome', 'blurred figure', 'serif heading', 'minimal form'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'welcome-portals', originalAsset: imageFile(3, 'jpg') },
    media: { poster: '/assets/posters/image-03.jpg', detailImage: imageFile(3, 'jpg'), original: imageFile(3, 'jpg') },
    quality: { tier: 'canonical', width: 2304, height: 1638, confidence: 0.98, reliableFor: ['layout', 'contrast', 'form styling', 'image treatment'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Use a clean authentication panel on the left and a soft-focus contemplative photograph on the right.', palette: 'paper white, mist grey, and deep charcoal', texture: 'fine film grain with intentionally softened photographic detail', motion: 'a slow breathing opacity shift in the photograph only', preserve: 'the emotional contrast between crisp form and hazy scene', avoid: 'busy backgrounds, heavy shadows, decorative form chrome' },
  },
  {
    id: 'image-castle-waitlist', order: 4, title: 'Castle Waitlist',
    styleDescriptor: 'Launch page / engraved fantasy mono',
    description: 'A minimal waitlist pairs an oversized serif announcement with a rough engraved fortress, combining product-launch clarity with storybook world-building.',
    primaryCategory: 'Dither Mono', extraFilters: ['Illustrated Storybook', 'Print-Tech Paper'],
    tags: ['engraving', 'waitlist form', 'serif display', 'black and white', 'asymmetric hero'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'castle-waitlist', originalAsset: imageFile(4, 'png') },
    media: { poster: '/assets/posters/image-04.jpg', detailImage: imageFile(4, 'png'), original: imageFile(4, 'png') },
    quality: { tier: 'canonical', width: 2880, height: 2048, confidence: 0.98, reliableFor: ['layout', 'illustration treatment', 'typography', 'form styling'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Place a compact signup message and input on the left while a monumental engraved castle occupies the right edge.', palette: 'pure white and ink black', texture: 'woodcut-style crosshatching with crisp interface rules', motion: 'static by default; a subtle engraved shimmer may appear on hover', preserve: 'the severe two-column balance and tactile monochrome illustration', avoid: 'fantasy-game UI chrome, ornamental borders, saturated color' },
  },
  {
    id: 'image-flora-footer', order: 5, title: 'Flora Field Notes',
    styleDescriptor: 'Illustrated footer / layered landscape',
    description: 'A richly layered footer turns navigation and newsletter utilities into a vivid pastoral scene, demonstrating how functional information can live inside illustration.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Reference Styles'],
    tags: ['layered landscape', 'footer system', 'bright palette', 'tiny navigation', 'character vignette'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'flora-field-notes', originalAsset: imageFile(5, 'jpg') },
    media: { poster: '/assets/posters/image-05.jpg', detailImage: imageFile(5, 'jpg'), original: imageFile(5, 'jpg') },
    quality: { tier: 'canonical', width: 2880, height: 2192, confidence: 0.97, reliableFor: ['illustration', 'palette', 'navigation grouping', 'footer composition'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Stack a dense utility navigation band above a panoramic illustrated field with newsletter content embedded into the scene.', palette: 'sky cyan, sunflower yellow, leaf green, coral, and cream', texture: 'flat vector shapes with hand-drawn foliage accents', motion: 'gentle parallax between mountain, field, and character layers', preserve: 'the integration of utility content with a joyful landscape', avoid: 'floating white cards that separate content from the illustration' },
  },
  {
    id: 'image-bloomride', order: 6, title: 'BloomRide Europe',
    styleDescriptor: 'Travel hero / playful vector atlas',
    description: 'A scenic cycling tour hero uses a compressed editorial headline, storybook landscape, and map-like trip controls to make booking feel exploratory.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Reference Styles'],
    tags: ['vector landscape', 'travel controls', 'condensed serif', 'bright sky', 'route planning'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'bloomride', originalAsset: imageFile(6, 'jpg') },
    media: { poster: '/assets/posters/image-06.jpg', detailImage: imageFile(6, 'jpg'), original: imageFile(6, 'jpg') },
    quality: { tier: 'canonical', width: 3018, height: 2184, confidence: 0.97, reliableFor: ['hero layout', 'illustration', 'palette', 'control grouping'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Anchor a large headline over a scenic illustrated world and dock a compact multi-field trip planner along the lower edge.', palette: 'clear sky blue, grass green, windmill red, cream, and warm yellow', texture: 'clean vector geometry with lightly imperfect botanical details', motion: 'animate windmill blades and drifting clouds slowly; controls remain stable', preserve: 'the sense of place, wide horizon, and practical route selector', avoid: 'photo-real travel imagery, glassmorphism, excessive badges' },
  },
  {
    id: 'image-voypix', order: 7, title: 'Voypix — One Pixel',
    styleDescriptor: 'Builder hero / pixel-classical collision',
    description: 'A restrained builder landing page interrupts a clean grid with pixelated reaching hands, combining product clarity, antiquity, and digital construction.',
    primaryCategory: 'Glitched Antiquity', extraFilters: ['Data-as-Texture', 'Classical Remix'],
    tags: ['pixel hands', 'classical motif', 'builder product', 'white space', 'mono UI'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'voypix', originalAsset: imageFile(7, 'jpg') },
    media: { poster: '/assets/posters/image-07.jpg', detailImage: imageFile(7, 'jpg'), original: imageFile(7, 'jpg') },
    quality: { tier: 'canonical', width: 2876, height: 2220, confidence: 0.98, reliableFor: ['layout', 'image treatment', 'typography', 'brand tone'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Keep the product proposition left-aligned and place two nearly touching pixel-rendered classical hands across the lower half.', palette: 'white, graphite, and granular grey', texture: 'dot-matrix pixels dissolving into clean negative space', motion: 'let pixels assemble toward the fingertip on entry, then settle', preserve: 'the creation metaphor, disciplined grid, and hybrid old/new language', avoid: 'literal developer screenshots, neon cyberpunk, ornate classical frames' },
  },
  {
    id: 'image-nova-stack', order: 8, title: 'Nova Developer Stack',
    styleDescriptor: 'Product utility / isometric infrastructure',
    description: 'A crisp software hero combines a direct headline with an isometric systems diagram and compact conversion controls, acting as a dependable reference baseline.',
    primaryCategory: 'Reference Styles', extraFilters: ['Data-as-Texture'],
    tags: ['isometric diagram', 'SaaS hero', 'product UI', 'soft grey', 'compact CTA'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'nova-stack', originalAsset: imageFile(8, 'jpg') },
    media: { poster: '/assets/posters/image-08.jpg', detailImage: imageFile(8, 'jpg'), original: imageFile(8, 'jpg') },
    quality: { tier: 'canonical', width: 2880, height: 2442, confidence: 0.98, reliableFor: ['layout', 'diagram treatment', 'typography', 'conversion pattern'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Place a concise product headline and two actions on the left with an airy isometric integration diagram on the right.', palette: 'white, cool grey, pale blue, and black', texture: 'clean vector edges with subtle grid and diagram shadows', motion: 'small connector pulses travel through the isometric stack', preserve: 'the immediate proposition and readable infrastructure metaphor', avoid: 'dense dashboard screenshots, multicolor gradients, inflated marketing copy' },
  },
  {
    id: 'image-auron-architecture', order: 9, title: 'Auron — Crafted for Visionaries',
    styleDescriptor: 'Architecture hero / engraved panorama',
    description: 'A classical architectural engraving framed by a rational landing-page shell produces a premium, intellectual tone without relying on photography.',
    primaryCategory: 'Classical Remix', extraFilters: ['Print-Tech Paper'],
    tags: ['architectural engraving', 'framed hero', 'serif display', 'paper texture', 'formal symmetry'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'auron-architecture', originalAsset: imageFile(9, 'png') },
    media: { poster: '/assets/posters/image-09.jpg', detailImage: imageFile(9, 'png'), original: imageFile(9, 'png') },
    quality: { tier: 'canonical', width: 2880, height: 2048, confidence: 0.98, reliableFor: ['layout', 'engraving texture', 'typography', 'formal tone'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Center a wide engraved city panorama inside a bordered content frame with a headline and paired actions overlaid near the bottom.', palette: 'ivory, graphite, and muted stone grey', texture: 'fine copperplate engraving over subtle paper grain', motion: 'a slow horizontal drift across the panorama with static interface framing', preserve: 'the formal border, antique city detail, and restrained CTA pair', avoid: 'gold luxury clichés, heavy drop shadows, photographic architecture' },
  },
  {
    id: 'image-vitra-waitlist', order: 10, title: 'Vitra — Good Things Are on the Way',
    styleDescriptor: 'Waitlist split / contemporary editorial illustration',
    description: 'A compact waitlist pairs oversized friendly type with a sunlit illustrated city scene, balancing conversion clarity and magazine-like personality.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Reference Styles'],
    tags: ['split hero', 'editorial illustration', 'waitlist', 'oversized type', 'sunlit palette'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'vitra-waitlist', originalAsset: imageFile(10, 'png') },
    media: { poster: '/assets/posters/image-10.jpg', detailImage: imageFile(10, 'png'), original: imageFile(10, 'png') },
    quality: { tier: 'usable', width: 759, height: 540, confidence: 0.9, reliableFor: ['layout', 'palette', 'illustration direction'], note: 'Moderate-resolution supplied image; avoid inferring small typography details.' },
    profile: { composition: 'Split the hero between a large friendly statement and an editorial illustration of a person in a sunlit urban garden.', palette: 'sage green, pale blue, warm cream, black, and leaf green', texture: 'flat painted shapes with lightly textured shadows', motion: 'subtle leaf movement and a slow shift in daylight', preserve: 'the approachable split, clear waitlist action, and human-scale scene', avoid: 'tiny decorative copy, generic 3D characters, excessive rounded containers' },
  },
  {
    id: 'image-launchpad-tools', order: 11, title: 'Launchpad Connections',
    styleDescriptor: 'Integration hero / luminous orbit',
    description: 'A highly restrained integration page centers a radial orbit of tool marks beneath a direct headline, using one luminous accent to focus attention.',
    primaryCategory: 'Reference Styles', extraFilters: ['Data-as-Texture'],
    tags: ['centered hero', 'integration orbit', 'luminous accent', 'white space', 'minimal nav'],
    source: { kind: 'image', captureMethod: 'original-upload', sourceGroupId: 'launchpad-tools', originalAsset: imageFile(11, 'jpg') },
    media: { poster: '/assets/posters/image-11.jpg', detailImage: imageFile(11, 'jpg'), original: imageFile(11, 'jpg') },
    quality: { tier: 'canonical', width: 4096, height: 2625, confidence: 0.97, reliableFor: ['layout', 'hierarchy', 'diagram direction', 'palette'], note: 'High-resolution supplied image.' },
    profile: { composition: 'Center a compact headline above a radial integration orbit with a luminous product core and generous empty margins.', palette: 'white, black, pearl grey, and one violet glow', texture: 'clean vector lines with a restrained bloom around the center', motion: 'logos orbit slowly while connection arcs pulse toward the core', preserve: 'the calm center, single accent color, and legible integration metaphor', avoid: 'constantly spinning icons, rainbow glows, crowded partner-logo walls' },
  },
  {
    id: 'image-stillness', order: 12, title: 'Stillness — Science of Practice',
    styleDescriptor: 'Meditation hero / voxel landscape',
    description: 'A calm meditation proposition sits above a voxel-like mountain and river landscape, using pixel geometry to make wellness feel precise rather than mystical.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Dither Mono'],
    tags: ['voxel landscape', 'wellness hero', 'serif headline', 'muted earth tones', 'wide scene'],
    source: { kind: 'image', siteName: 'Stillness', captureMethod: 'youtube-frame', sourceGroupId: 'stillness', originalAsset: imageFile(12, 'png') },
    media: { poster: '/assets/posters/image-12.jpg', detailImage: imageFile(12, 'png'), original: imageFile(12, 'png') },
    quality: { tier: 'usable', width: 837, height: 495, confidence: 0.78, reliableFor: ['composition', 'palette', 'illustration direction'], note: 'YouTube-derived frame; reliable for broad composition but not fine typography or texture.' },
    profile: { composition: 'Place a concise wellness proposition in the upper left and let a voxel mountain valley fill the lower two-thirds.', palette: 'warm white, deep teal, moss green, coral clay, and pale stone', texture: 'blocky voxel terrain softened by atmospheric haze', motion: 'very slow river shimmer and drifting mist between mountain layers', preserve: 'the grounded science tone and expansive geometric landscape', avoid: 'spiritual symbols, glowing auras, unreadable small text' },
  },
  {
    id: 'image-linq-recovered', order: 13, title: 'Linq Messaging',
    styleDescriptor: 'Developer platform / cinematic message layer',
    description: 'A product headline and floating conversation UI sit over a cinematic illustrated landscape, making communications infrastructure feel immediate and human.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Reference Styles'],
    tags: ['cinematic landscape', 'floating message UI', 'developer product', 'dark overlay', 'bright CTA'],
    source: { kind: 'website', siteName: 'Linq', url: 'https://linqapp.com/', captureMethod: 'recovered-live', capturedAt: '2026-08-21', sourceGroupId: 'linq', originalAsset: imageFile(13, 'png') },
    media: { poster: '/assets/posters/image-13.jpg', detailImage: '/assets/site-captures/13-linq.png', original: imageFile(13, 'png'), motionNotes: 'The landscape and conversational elements introduce depth while the headline and conversion controls remain anchored.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['layout', 'typography', 'palette', 'UI layering'], note: 'Recovered as a current live 1440×900 browser capture; the original video frame remains archived.' },
    profile: { composition: 'Layer a translucent messaging card over a full-width cinematic landscape, then anchor the headline and actions along the lower center.', palette: 'deep forest green, blue-grey sky, charcoal overlay, white, and an electric lime CTA', texture: 'soft atmospheric illustration behind crisp glass-like message surfaces', motion: 'message bubbles arrive sequentially while the landscape holds a slow ambient drift', preserve: 'the human message exchange and deep environmental staging', avoid: 'busy chat timelines, tiny code samples, excessive glass blur' },
  },
  {
    id: 'image-yieldstream', order: 14, title: 'Yieldstream Celestial',
    styleDescriptor: 'Finance hero / orbital antiquity',
    description: 'A classical winged figure cuts across a near-black financial interface scattered with planets and data, turning yield aggregation into a cosmic myth.',
    primaryCategory: 'Glitched Antiquity', extraFilters: ['Classical Remix', 'Data-as-Texture'],
    tags: ['celestial figure', 'financial data', 'orbital diagram', 'dark canvas', 'serif headline', 'scan artifacts'],
    source: { kind: 'image', siteName: 'Yieldstream', captureMethod: 'youtube-frame', sourceGroupId: 'yieldstream', originalAsset: imageFile(14, 'png') },
    media: { poster: '/assets/posters/image-14.jpg', detailImage: imageFile(14, 'png'), original: imageFile(14, 'png') },
    quality: { tier: 'limited', width: 541, height: 334, confidence: 0.62, reliableFor: ['composition', 'broad palette', 'visual metaphor'], note: 'Low-resolution YouTube frame with playback contamination; do not infer fine type, spacing, or data labels.' },
    profile: { composition: 'Set a large serif financial proposition on the left and a monumental winged classical figure on the right, surrounded by orbital data fragments.', palette: 'near black, parchment cream, faded peach, and small spectral accents', texture: 'archival engraving, scan noise, pixel dust, and fine data ticks', motion: 'planets orbit slowly while fragments flicker around the figure', preserve: 'the mythic scale and fusion of finance, cosmos, and antiquity', avoid: 'copying unreadable labels, literal crypto coins, neon trading dashboards' },
  },
  {
    id: 'image-marble-recovered', order: 15, title: 'Marble Learning World',
    styleDescriptor: 'Kids learning hero / cinematic island',
    description: 'A child paddles toward a fantastical island beneath an enormous cloud-filled wordmark, framing learning as a vivid world to explore.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Vast Quiet Cinematic'],
    tags: ['ocean world', 'giant wordmark', 'child explorer', 'cloud typography', 'bright CTA'],
    source: { kind: 'website', siteName: 'Marble', url: 'https://withmarble.com/', captureMethod: 'recovered-live', capturedAt: '2026-08-21', sourceGroupId: 'marble', originalAsset: imageFile(15, 'png') },
    media: { poster: '/assets/posters/image-15.jpg', detailImage: '/assets/site-captures/15-marble.png', original: imageFile(15, 'png'), motionNotes: 'The scene behaves like a living title card: water, clouds, and the child’s approach imply continuous exploration.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['composition', 'typography scale', 'palette', 'illustration'], note: 'Recovered as a current live 1440×900 browser capture; the original video frame remains archived.' },
    profile: { composition: 'Fill the frame with open ocean, place an enormous rounded wordmark across the sky, and guide a small child toward a distant fantasy island.', palette: 'saturated ocean blue, cloud white, warm skin tones, and a single red action', texture: 'soft cinematic clouds, glossy water, and painterly island detail', motion: 'water ripples, clouds drift, and the kayak moves slowly toward the island', preserve: 'the dramatic scale contrast and optimistic sense of discovery', avoid: 'toy-like UI chrome, crowded educational badges, generic cartoon mascots' },
  },
  {
    id: 'image-break-pattern', order: 16, title: 'Break the Pattern',
    styleDescriptor: 'Coaching hero / Renaissance collage',
    description: 'A coaching proposition overlays a blue-toned reinterpretation of two reaching hands, turning familiar Renaissance imagery into a contemporary transformation message.',
    primaryCategory: 'Classical Remix', extraFilters: ['Print-Tech Paper'],
    tags: ['reaching hands', 'renaissance crop', 'blue texture', 'centered serif', 'coaching CTA'],
    source: { kind: 'image', captureMethod: 'youtube-frame', sourceGroupId: 'break-pattern', originalAsset: imageFile(16, 'png') },
    media: { poster: '/assets/posters/image-16.jpg', detailImage: imageFile(16, 'png'), original: imageFile(16, 'png') },
    quality: { tier: 'limited', width: 540, height: 334, confidence: 0.68, reliableFor: ['composition', 'broad palette', 'classical reference'], note: 'Low-resolution YouTube frame; reliable for concept and hierarchy only.' },
    profile: { composition: 'Crop two reaching classical hands across the upper half and center a transformation headline and paired actions beneath their fingertips.', palette: 'dusty blue, warm skin, cloud white, and ink black', texture: 'aged fresco grain with faint diagram lines', motion: 'the hands remain still while fine circular guide lines rotate almost imperceptibly', preserve: 'the charged gap between hands and the centered promise', avoid: 'religious claims, literal reproduction of the artwork, fine text inferred from the frame' },
  },
  {
    id: 'image-market-predictions', order: 17, title: 'Global Prediction Field',
    styleDescriptor: 'Market interface / ASCII globe',
    description: 'A restrained analytics page turns a globe into a field of tiny marks, balancing editorial copy, tabbed sectors, and a highly technical visual center.',
    primaryCategory: 'Data-as-Texture', extraFilters: ['Print-Tech Paper'],
    tags: ['ASCII globe', 'market data', 'tabbed interface', 'micro typography', 'white canvas'],
    source: { kind: 'image', captureMethod: 'youtube-frame', sourceGroupId: 'market-predictions', originalAsset: imageFile(17, 'png') },
    media: { poster: '/assets/posters/image-17.jpg', detailImage: imageFile(17, 'png'), original: imageFile(17, 'png') },
    quality: { tier: 'limited', width: 542, height: 333, confidence: 0.64, reliableFor: ['composition', 'data visualization direction', 'broad hierarchy'], note: 'Low-resolution YouTube frame with a video label; do not infer small copy or exact plotting data.' },
    profile: { composition: 'Use a wide bordered canvas with an ASCII globe occupying the left two-thirds, a compact explanation at upper right, and category tabs along the base.', palette: 'white, ink black, and faint lavender-grey', texture: 'microtype, dot fields, and sparse grid ticks', motion: 'data points sweep around the globe in slow vertical bands', preserve: 'the globe-as-texture idea and large quiet analytical canvas', avoid: 'fabricated readable data, conventional chart dashboards, bright chart palettes' },
  },
  {
    id: 'image-juris', order: 18, title: 'Juris Legal Intelligence',
    styleDescriptor: 'Legal AI hero / allegorical sky',
    description: 'A legal assistant interface pairs a direct question box with a monumental allegorical justice figure, making an abstract service feel approachable and authoritative.',
    primaryCategory: 'Classical Remix', extraFilters: ['Illustrated Storybook', 'Reference Styles'],
    tags: ['justice figure', 'blue sky', 'AI input', 'classical allegory', 'split hero'],
    source: { kind: 'image', siteName: 'Juris', captureMethod: 'youtube-frame', sourceGroupId: 'juris', originalAsset: imageFile(18, 'png') },
    media: { poster: '/assets/posters/image-18.jpg', detailImage: imageFile(18, 'png'), original: imageFile(18, 'png') },
    quality: { tier: 'limited', width: 541, height: 333, confidence: 0.66, reliableFor: ['composition', 'broad palette', 'visual metaphor'], note: 'Low-resolution YouTube frame; do not rely on small interface labels or exact sculpture detail.' },
    profile: { composition: 'Place a concise legal proposition and question composer on the left while an allegorical justice figure rises through clouds on the right.', palette: 'clear sky blue, cloud white, warm marble peach, and charcoal text', texture: 'soft painted clouds and sculptural fabric against crisp UI surfaces', motion: 'clouds drift and the figure enters with a slow vertical reveal', preserve: 'the accessible input, monumental allegory, and confident open sky', avoid: 'dense legal document UI, ornate courthouse motifs, copied brand marks' },
  },
];

const siteSeeds: Seed[] = [
  {
    id: 'site-notion', order: 19, title: 'Notion — Teams and Agents', styleDescriptor: 'Product ecosystem / playful clarity',
    description: 'A familiar productivity layout sharpens a large direct proposition with small illustrated product emblems and an unusually broad proof row.',
    primaryCategory: 'Reference Styles', tags: ['direct headline', 'product emblems', 'white canvas', 'proof logos', 'blue CTA'],
    source: { kind: 'website', siteName: 'Notion', url: 'https://www.notion.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'notion', originalAsset: '/assets/site-captures/01-notion.png' },
    media: { poster: '/assets/posters/site-01.jpg', detailImage: '/assets/site-captures/01-notion.png', original: '/assets/site-captures/01-notion.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['layout', 'typography', 'conversion pattern', 'brand system'], note: 'Current live browser capture.' },
    profile: { composition: 'Center an oversized proposition with small illustrated product emblems above and a wide customer-proof strip below.', palette: 'white, ink black, Notion-like blue, and tiny multicolor accents', texture: 'clean vector icons and crisp interface surfaces', motion: 'small emblems drift or respond while headline and actions remain stable', preserve: 'immediate readability and the playful product constellation', avoid: 'cloning brand logos, decorative backgrounds, long paragraphs' },
  },
  {
    id: 'site-spade', order: 20, title: 'Spade', styleDescriptor: 'Finance platform / print-tech anatomy',
    description: 'A finance proposition is staged on pale green paper with anatomical line art, transaction fragments, and ruler-like edge markings.',
    primaryCategory: 'Print-Tech Paper', extraFilters: ['Data-as-Texture'], tags: ['pale green', 'anatomical engraving', 'finance data', 'ruler marks', 'black type'],
    source: { kind: 'website', siteName: 'Spade', url: 'https://spade.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'spade', originalAsset: '/assets/site-captures/02-spade.png' },
    media: { poster: '/assets/posters/site-02.jpg', detailImage: '/assets/site-captures/02-spade.png', original: '/assets/site-captures/02-spade.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['layout', 'typography', 'palette', 'engraving treatment'], note: 'Current live browser capture.' },
    profile: { composition: 'Place a bold finance headline in the upper center, then layer an engraved hand, transaction receipt, and measurement ticks across the lower plane.', palette: 'pale sage paper, black ink, white, and restrained green', texture: 'technical engraving, ledger marks, and thin measurement rules', motion: 'receipt values update gently while the engraved hand shifts in parallax', preserve: 'the financial clarity and tactile technical-paper character', avoid: 'banking stock photos, glossy gradients, generic chart cards' },
  },
  {
    id: 'site-sstr', order: 21, title: 'SSTR Friction Systems', styleDescriptor: 'Industrial hero / monumental machinery',
    description: 'A drilling component is treated as a black monument against a soft industrial horizon, with compact utility copy and a single high-energy action.',
    primaryCategory: 'Data-as-Texture', extraFilters: ['Vast Quiet Cinematic'], tags: ['industrial object', 'soft horizon', 'orange CTA', 'technical nav', 'monumental crop'],
    source: { kind: 'website', siteName: 'SSTR', url: 'https://sstr.tech/en/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'sstr', originalAsset: '/assets/site-captures/03-sstr.png' },
    media: { poster: '/assets/posters/site-03.jpg', detailImage: '/assets/site-captures/03-sstr.png', original: '/assets/site-captures/03-sstr.png', motionNotes: 'The hero relies on loader-to-object reveal, subtle camera movement, and a stable technical information layer.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 0.98, reliableFor: ['composition', 'object scale', 'palette', 'hierarchy'], note: 'Current post-loader live capture.' },
    profile: { composition: 'Crop a single industrial tool as a vertical monument in the center and position technical copy along the left third.', palette: 'warm grey, black, dust beige, white, and safety orange', texture: 'matte machined metal against a soft granular horizon', motion: 'reveal the object from a dark loader, then use slow camera drift and restrained data transitions', preserve: 'the object scale, industrial restraint, and one sharp action color', avoid: 'busy spec sheets, multiple bright buttons, generic factory footage' },
  },
  {
    id: 'site-watch', order: 22, title: 'FS60P Watch', styleDescriptor: 'Product selector / typographic monument',
    description: 'A compact mechanical watch interrupts enormous condensed lettering, using an ultra-clean selector interface and precision-line geometry.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Reference Styles'], tags: ['giant type', 'product cutout', 'precision lines', 'silver palette', 'selector UI'],
    source: { kind: 'website', siteName: 'FS60P', url: 'https://thewatch.60fps.fr/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'fs60p', originalAsset: '/assets/site-captures/04-the-watch.png' },
    media: { poster: '/assets/posters/site-04.jpg', detailImage: '/assets/site-captures/04-the-watch.png', original: '/assets/site-captures/04-the-watch.png', motionNotes: 'The watch rotates and selector states shift within a fixed typographic stage.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['composition', 'type scale', 'product staging', 'interface restraint'], note: 'Current post-loader live capture.' },
    profile: { composition: 'Stretch an enormous model name edge to edge, suspend a precisely rendered watch at center, and keep selector metadata in the corners.', palette: 'silver, white, soft grey, and black', texture: 'polished metal, fine vector arcs, and a seamless studio field', motion: 'rotate the watch slowly with crisp model-to-model transitions', preserve: 'the type/object collision and extremely restrained controls', avoid: 'luxury black-and-gold clichés, lifestyle photography, crowded spec tables' },
  },
  {
    id: 'site-igloo', order: 23, title: 'Igloo Inc.', styleDescriptor: 'Monochrome world / sculptural studio',
    description: 'A crystalline igloo sits in a vast grayscale mountain world, surrounded by tiny interface annotations that make the scene feel exploratory and authored.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Dither Mono'], tags: ['monochrome 3D', 'mountain world', 'crystal object', 'micro labels', 'ambient scene'],
    source: { kind: 'website', siteName: 'Igloo Inc.', url: 'https://www.igloo.inc/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'igloo', originalAsset: '/assets/site-captures/05-igloo.png' },
    media: { poster: '/assets/posters/site-05.jpg', detailImage: '/assets/site-captures/05-igloo.png', original: '/assets/site-captures/05-igloo.png', motionNotes: 'The scene uses slow environmental camera motion and subtle crystalline response.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['environmental staging', 'palette', 'micro-interface balance'], note: 'Current post-loader live capture.' },
    profile: { composition: 'Place a translucent igloo slightly off center in a wide mountain basin and distribute tiny studio metadata around the frame edges.', palette: 'snow white, graphite, mist grey, and glassy highlights', texture: 'grainy terrain, translucent ice blocks, and fine wireframe annotations', motion: 'use slow camera orbit, fog drift, and restrained crystal refraction', preserve: 'the solitude, object clarity, and tiny edge annotations', avoid: 'bright color, conventional portfolio grids, fast 3D camera moves' },
  },
  {
    id: 'site-dont-board-me', order: 24, title: 'Don’t Board Me', styleDescriptor: 'Interactive entrance / single playful dare',
    description: 'A bubblegum-pink gate reduces entry to one oversized instruction: bounce a ball to reveal the site.',
    primaryCategory: 'Reference Styles', extraFilters: ['Illustrated Storybook'], tags: ['interactive gate', 'pink field', 'bold condensed type', 'ball physics', 'single instruction'],
    source: { kind: 'website', siteName: 'Don’t Board Me', url: 'https://dontboardme.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'dont-board-me', originalAsset: '/assets/site-captures/06-dont-board-me.png' },
    media: { poster: '/assets/posters/site-06.jpg', detailImage: '/assets/site-captures/06-dont-board-me.png', original: '/assets/site-captures/06-dont-board-me.png', motionNotes: 'A simple ball-physics interaction turns the entrance state into a memorable act of participation.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['interaction concept', 'type scale', 'palette'], note: 'Current entrance-state capture.' },
    profile: { composition: 'Center one oversized condensed instruction on an uninterrupted color field with a small interactive ball beside it.', palette: 'bubblegum pink, hot red, and one lemon accent', texture: 'flat saturated color with crisp letterforms', motion: 'the ball follows believable bounce physics and unlocks the next state', preserve: 'the single playful task and immediate visual confidence', avoid: 'tutorial overlays, multiple instructions, ornamental graphics' },
  },
  {
    id: 'site-opal', order: 25, title: 'Opal — The Table', styleDescriptor: 'Editorial product story / dense image column',
    description: 'A dense column of close-up product imagery runs beside a narrow editorial text block, creating the feel of a contemporary product monograph.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Print-Tech Paper'], tags: ['editorial split', 'product close-ups', 'narrow copy', 'dark canvas', 'vertical sequence'],
    source: { kind: 'website', siteName: 'Opal', url: 'https://op.al/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'opal', originalAsset: '/assets/site-captures/07-opal.png' },
    media: { poster: '/assets/posters/site-07.jpg', detailImage: '/assets/site-captures/07-opal.png', original: '/assets/site-captures/07-opal.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['editorial layout', 'image sequencing', 'type scale'], note: 'Current live capture.' },
    profile: { composition: 'Dedicate most of the frame to a vertical mosaic of intimate product images and reserve a narrow column for title and essay text.', palette: 'black, warm cream, steel blue, and incidental product colors', texture: 'high-detail material photography against matte editorial surfaces', motion: 'scroll the image column at a distinct pace from the anchored text', preserve: 'the monograph density and confident asymmetry', avoid: 'equal-sized product cards, obvious ecommerce chrome, oversized CTA buttons' },
  },
  {
    id: 'site-lusion', order: 26, title: 'Lusion Studio', styleDescriptor: '3D portfolio / modular playfield',
    description: 'A precise studio statement sits above an interactive tray of abstract 3D components, treating capability proof as a playable construction set.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Reference Styles'], tags: ['interactive 3D', 'modular objects', 'studio statement', 'white canvas', 'playful physics'],
    source: { kind: 'website', siteName: 'Lusion', url: 'https://lusion.co/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'lusion', originalAsset: '/assets/site-captures/08-lusion.png' },
    media: { poster: '/assets/posters/site-08.jpg', detailImage: '/assets/site-captures/08-lusion.png', original: '/assets/site-captures/08-lusion.png', motionNotes: 'Abstract objects respond with WebGL depth and physical play while the studio framing stays spare.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 0.98, reliableFor: ['layout', '3D art direction', 'interaction framing'], note: 'Current interactive hero capture.' },
    profile: { composition: 'Keep a concise studio statement in a narrow top band and place a large interactive tray of abstract 3D objects beneath it.', palette: 'white, black, cobalt blue, lavender, and charcoal', texture: 'soft matte 3D materials with studio lighting', motion: 'objects respond to pointer movement with restrained physics and depth', preserve: 'the playfield framing and contrast between sober copy and playful objects', avoid: 'full-screen visual noise, excessive camera rotation, decorative gradients' },
  },
  {
    id: 'site-mana', order: 27, title: 'MANA Yerba Mate', styleDescriptor: 'Botanical packaging / exuberant collage',
    description: 'A bright can is surrounded by hand-cut fruit, flowers, sun shapes, and bold lettering, creating an energetic packaging-led world.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Print-Tech Paper'], tags: ['botanical collage', 'packaging hero', 'cut-paper shapes', 'lime green', 'playful lettering'],
    source: { kind: 'website', siteName: 'MANA Yerba Mate', url: 'https://en.manayerbamate.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'mana', originalAsset: '/assets/site-captures/09-mana.png' },
    media: { poster: '/assets/posters/site-09.jpg', detailImage: '/assets/site-captures/09-mana.png', original: '/assets/site-captures/09-mana.png', motionNotes: 'Illustrated ingredients and packaging elements bounce, slide, and layer around the fixed product can.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['palette', 'collage composition', 'packaging staging', 'motion direction'], note: 'Current live capture.' },
    profile: { composition: 'Center a beverage can and surround it with oversized cut-paper fruit, leaves, flowers, and expressive lettering.', palette: 'lime green, coral red, cream, leaf green, orange, and black', texture: 'paper-cut illustration with chunky hand-drawn marks', motion: 'ingredients bounce and slide in layered loops around a stable can', preserve: 'the bold product focus and joyful botanical density', avoid: 'photo-real fruit splashes, glossy beverage clichés, tiny ingredient copy' },
  },
  {
    id: 'site-orano', order: 28, title: 'Orano Innovation', styleDescriptor: 'Industrial documentary / split manifesto',
    description: 'A documentary worker portrait occupies one half of the frame while a near-black manifesto panel carries a sparse innovation statement.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Reference Styles'], tags: ['documentary portrait', 'split screen', 'industrial story', 'black panel', 'spaced type'],
    source: { kind: 'website', siteName: 'Orano', url: 'https://www.orano.group/experience/innovation/en', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'orano', originalAsset: '/assets/site-captures/10-orano.png' },
    media: { poster: '/assets/posters/site-10.jpg', detailImage: '/assets/site-captures/10-orano.png', original: '/assets/site-captures/10-orano.png', motionNotes: 'The entrance behaves as a cinematic split title card with controlled transitions into the experience.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['split composition', 'portrait crop', 'typography', 'tone'], note: 'Current entrance-state capture.' },
    profile: { composition: 'Split the viewport evenly between a candid industrial worker portrait and a dark manifesto panel with a small enter action.', palette: 'charcoal, steel grey, workwear blue, white, and a restrained yellow accent', texture: 'documentary photography paired with a perfectly matte panel', motion: 'use a slow cinematic reveal and a precise split-panel transition on entry', preserve: 'the human credibility and severe manifesto typography', avoid: 'corporate iconography, multiple content cards, cheerful stock photography' },
  },
  {
    id: 'site-snows', order: 29, title: 'SNOWS Winter', styleDescriptor: 'Seasonal confectionery / illustrated storefront',
    description: 'A winter-blue illustrated awning frames chocolate products, character packaging, and tactile treats like a miniature seasonal shop window.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Reference Styles'], tags: ['winter awning', 'product tableau', 'packaging characters', 'powder blue', 'seasonal retail'],
    source: { kind: 'website', siteName: 'SNOWS', url: 'https://snows-winter.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'snows', originalAsset: '/assets/site-captures/11-snows.png' },
    media: { poster: '/assets/posters/site-11.jpg', detailImage: '/assets/site-captures/11-snows.png', original: '/assets/site-captures/11-snows.png', motionNotes: 'Masked logo and shop-window elements reveal in a playful seasonal sequence.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['retail staging', 'illustration', 'palette', 'product grouping'], note: 'Current live capture.' },
    profile: { composition: 'Create a front-facing seasonal shop window with a scalloped awning above and products arranged in a horizontal tabletop tableau.', palette: 'powder blue, snow white, chocolate brown, charcoal, and small pastel accents', texture: 'paper packaging, chocolate surfaces, and soft painted winter details', motion: 'reveal products in sequence and let hanging or masked elements sway gently', preserve: 'the storefront framing and tactile product variety', avoid: 'generic ecommerce grids, holiday red and green, heavy promotional badges' },
  },
  {
    id: 'site-x-advertising', order: 30, title: 'X Advertising', styleDescriptor: 'Product explainer / diagrammatic proof',
    description: 'A direct performance headline sits beside a large ruled diagram of conversations, charts, and value blocks, turning an abstract ad product into a system map.',
    primaryCategory: 'Data-as-Texture', extraFilters: ['Reference Styles'], tags: ['system diagram', 'ruled grid', 'value blocks', 'grotesk headline', 'product proof'],
    source: { kind: 'website', siteName: 'X Business', url: 'https://business.x.com/en/advertising', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'x-advertising', originalAsset: '/assets/site-captures/12-x-advertising.png' },
    media: { poster: '/assets/posters/site-12.jpg', detailImage: '/assets/site-captures/12-x-advertising.png', original: '/assets/site-captures/12-x-advertising.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['diagram composition', 'grid', 'hierarchy'], note: 'Current live capture.' },
    profile: { composition: 'Place a concise headline on the left and devote most of the canvas to a ruled diagram connecting messages, charts, and value markers.', palette: 'white, near black, soft grey, and minimal blue', texture: 'fine rules, technical boxes, and sparse diagram annotation', motion: 'animate connections sequentially to explain the system without moving the page structure', preserve: 'the diagram-first proof and high information clarity', avoid: 'social feed mockups, decorative data, multicolor analytics cards' },
  },
  {
    id: 'site-schemas', order: 31, title: 'Schemas of Uncertainty', styleDescriptor: 'Research essay / ASCII terrain',
    description: 'An essay index floats over an uninterrupted horizontal field of dense ASCII marks, making uncertainty itself feel like a navigable information landscape.',
    primaryCategory: 'Data-as-Texture', extraFilters: ['Print-Tech Paper'], tags: ['ASCII field', 'research essay', 'horizontal canvas', 'micro text', 'white space'],
    source: { kind: 'website', siteName: 'Schemas of Uncertainty', url: 'https://schemasofuncertainty.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'schemas', originalAsset: '/assets/site-captures/13-schemas.png' },
    media: { poster: '/assets/posters/site-13.jpg', detailImage: '/assets/site-captures/13-schemas.png', original: '/assets/site-captures/13-schemas.png', motionNotes: 'The key gesture is horizontal exploration across a continuous ASCII information field.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['data texture', 'density contrast', 'editorial framing'], note: 'Current live capture.' },
    profile: { composition: 'Stretch a dense ASCII research field far beyond the viewport and overlay a restrained article index and title along the top.', palette: 'paper white, ink black, and rare soft grey', texture: 'continuous monospace marks, typographic noise, and thin editorial rules', motion: 'use deliberate horizontal navigation through the data field', preserve: 'the contrast between extreme information density and calm margins', avoid: 'conventional cards, colorful charts, forced vertical scrolling' },
  },
  {
    id: 'site-apple', order: 32, title: 'Apple Promotional Hero', styleDescriptor: 'Campaign baseline / product-led clarity',
    description: 'A current Apple campaign demonstrates the durable product-marketing baseline: minimal navigation, centered seasonal copy, and a large, immaculate visual stage.',
    primaryCategory: 'Reference Styles', tags: ['campaign hero', 'centered copy', 'product stage', 'minimal nav', 'white canvas'],
    source: { kind: 'website', siteName: 'Apple', url: 'https://www.apple.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'apple', originalAsset: '/assets/site-captures/14-apple.png' },
    media: { poster: '/assets/posters/site-14.jpg', detailImage: '/assets/site-captures/14-apple.png', original: '/assets/site-captures/14-apple.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['campaign hierarchy', 'spacing', 'conversion restraint'], note: 'Current live campaign capture; content is expected to change over time.' },
    profile: { composition: 'Center one short campaign promise above a pristine product or people-led stage, with navigation reduced to a thin top band.', palette: 'white, black, and a small set of product-led accent colors', texture: 'immaculate photography or high-fidelity rendering with no decorative surface', motion: 'use polished product reveals and restrained scroll choreography', preserve: 'the clarity, scale, and disciplined conversion hierarchy', avoid: 'copying Apple products or trademarks, excessive feature lists, ornamental UI' },
  },
  {
    id: 'site-clou', order: 33, title: 'CLOU Architects', styleDescriptor: 'Studio manifesto / rotating declaration',
    description: 'A nearly empty architectural stage turns the phrase “We are…” into a sequence of changing declarations, letting typography carry the portfolio entrance.',
    primaryCategory: 'Reference Styles', extraFilters: ['Vast Quiet Cinematic'], tags: ['rotating statement', 'architectural studio', 'white field', 'black label', 'minimal entrance'],
    source: { kind: 'website', siteName: 'CLOU Architects', url: 'https://www.clouarchitects.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'clou', originalAsset: '/assets/site-captures/15-clou.png' },
    media: { poster: '/assets/posters/site-15.jpg', detailImage: '/assets/site-captures/15-clou.png', original: '/assets/site-captures/15-clou.png', motionNotes: 'The identity is expressed through a timed sequence of professions and positions rather than a static claim.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 0.98, reliableFor: ['typographic stage', 'timing concept', 'minimal composition'], note: 'Current post-loader statement capture.' },
    profile: { composition: 'Leave almost the entire viewport empty and center a black label containing one rotating “We are…” declaration.', palette: 'white and black only', texture: 'perfectly flat surfaces with tiny architectural navigation', motion: 'replace the final word on a measured cadence with clean cuts or masks', preserve: 'the radical emptiness and identity-through-sequence idea', avoid: 'portfolio thumbnails in the opening frame, background video, ornamental motion' },
  },
  {
    id: 'site-system-patch', order: 34, title: 'System — Patch', styleDescriptor: 'Case study / disciplined brand panels',
    description: 'A brand case study opens with a black identity block, a pale product-information column, and a generous tactile image—an exemplary portfolio composition.',
    primaryCategory: 'Reference Styles', extraFilters: ['Print-Tech Paper'], tags: ['case study', 'panel grid', 'brand mark', 'tactile crop', 'editorial spacing'],
    source: { kind: 'website', siteName: 'System Studio', url: 'https://system.studio/work/patch', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'system-patch', originalAsset: '/assets/site-captures/16-system-patch.png' },
    media: { poster: '/assets/posters/site-16.jpg', detailImage: '/assets/site-captures/16-system-patch.png', original: '/assets/site-captures/16-system-patch.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['case-study structure', 'panel proportions', 'brand presentation'], note: 'Current live case-study capture.' },
    profile: { composition: 'Divide the hero into three unequal vertical panels: identity mark, concise project context, and a tactile product photograph.', palette: 'black, warm white, pale cream, and natural skin or product color', texture: 'matte brand panels beside detailed close-up photography', motion: 'use clean panel reveals and gentle image cropping shifts on scroll', preserve: 'the asymmetric panel logic and disciplined case-study context', avoid: 'portfolio carousels, decorative device mockups, long copy above the fold' },
  },
  {
    id: 'site-oqoqo', order: 35, title: 'Oqoqo Evals', styleDescriptor: 'AI product / evidence-first utility',
    description: 'A plainspoken evaluation product pairs a readable proposition with a real interface excerpt and small proof marks, emphasizing utility over spectacle.',
    primaryCategory: 'Reference Styles', extraFilters: ['Data-as-Texture'], tags: ['AI product', 'evidence UI', 'plainspoken copy', 'white canvas', 'compact proof'],
    source: { kind: 'website', siteName: 'Oqoqo', url: 'https://oqoqo.ai/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'oqoqo', originalAsset: '/assets/site-captures/17-oqoqo.png' },
    media: { poster: '/assets/posters/site-17.jpg', detailImage: '/assets/site-captures/17-oqoqo.png', original: '/assets/site-captures/17-oqoqo.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['product hierarchy', 'copy density', 'proof placement'], note: 'Current live capture.' },
    profile: { composition: 'Set a concise product proposition on the left and place a cropped, believable evaluation interface beneath and to the right.', palette: 'white, black, cool grey, and tiny status accents', texture: 'crisp product UI with minimal decorative treatment', motion: 'use only purposeful interface state transitions or a slow proof-carousel shift', preserve: 'the evidence-first message and honest product surface', avoid: 'AI sparkle icons, nebulous gradients, fake chat bubbles' },
  },
  {
    id: 'site-human-made', order: 36, title: 'Human Made Inc.', styleDescriptor: 'Brand entrance / iconic restraint',
    description: 'A heart-and-rays mark and compact wordmark float in a near-empty field, relying on a loader-to-logo reveal and exquisite spacing.',
    primaryCategory: 'Reference Styles', extraFilters: ['Dither Mono'], tags: ['iconic mark', 'centered identity', 'white space', 'black and white', 'micro navigation'],
    source: { kind: 'website', siteName: 'Human Made', url: 'https://humanmade.co.jp/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'human-made', originalAsset: '/assets/site-captures/18-human-made.png' },
    media: { poster: '/assets/posters/site-18.jpg', detailImage: '/assets/site-captures/18-human-made.png', original: '/assets/site-captures/18-human-made.png', motionNotes: 'A long, controlled loading sequence resolves into a centered identity mark with tiny edge navigation.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 0.98, reliableFor: ['identity staging', 'spacing', 'monochrome hierarchy'], note: 'Current post-loader live capture.' },
    profile: { composition: 'Center a simple high-recognition symbol and compact wordmark in a broad white field with tiny navigation pinned to the edges.', palette: 'white and ink black', texture: 'crisp vector identity with no decorative surface', motion: 'use a deliberate loader and one precise logo reveal, then become still', preserve: 'the confidence, empty field, and tiny edge controls', avoid: 'adding descriptive copy, decorative backgrounds, looping logo tricks' },
  },
  {
    id: 'site-notom', order: 37, title: 'Notom', styleDescriptor: 'Outdoor campaign / monochrome film',
    description: 'A grainy black-and-white outdoor scene is overlaid with compact campaign copy and small product controls, producing a raw editorial storefront.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Dither Mono'], tags: ['monochrome film', 'outdoor campaign', 'grain', 'compact overlay', 'raw editorial'],
    source: { kind: 'website', siteName: 'Notom', url: 'https://notom.co/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'notom', originalAsset: '/assets/site-captures/19-notom.png' },
    media: { poster: '/assets/posters/site-19.jpg', detailImage: '/assets/site-captures/19-notom.png', original: '/assets/site-captures/19-notom.png', motionClip: '/assets/motion/notom-hero.mp4', motionNotes: 'The full-bleed campaign film supplies environmental motion while the commerce overlay stays compact and stable.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['film treatment', 'overlay hierarchy', 'motion direction'], note: 'Current live capture plus a locally stored source video asset.' },
    profile: { composition: 'Fill the viewport with grainy monochrome outdoor film and anchor a small campaign title, price, and action in the lower left.', palette: 'black, white, and smoky grey', texture: 'coarse film grain, deep shadow, and soft motion blur', motion: 'loop a slow atmospheric outdoor film behind a fixed commerce overlay', preserve: 'the raw film character and tiny utilitarian interface', avoid: 'color grading, large ecommerce cards, polished studio photography' },
  },
  {
    id: 'site-more-nutrition', order: 38, title: 'More Nutrition Matcha', styleDescriptor: 'Packaging campaign / bold monochrome green',
    description: 'A matcha product pack and can are staged against a tightly controlled green field with huge cropped brand lettering and energetic nutrition notes.',
    primaryCategory: 'Print-Tech Paper', extraFilters: ['Illustrated Storybook'], tags: ['matcha green', 'giant wordmark', 'packaging hero', 'nutrition callouts', 'handwritten notes'],
    source: { kind: 'website', siteName: 'More Nutrition', url: 'https://more-nutrition.webflow.io/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'more-nutrition', originalAsset: '/assets/site-captures/20-more-nutrition.png' },
    media: { poster: '/assets/posters/site-20.jpg', detailImage: '/assets/site-captures/20-more-nutrition.png', original: '/assets/site-captures/20-more-nutrition.png', motionNotes: 'Packaging and nutrition marks animate into a tightly staged campaign frame after the loader.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['packaging staging', 'type scale', 'palette', 'callout rhythm'], note: 'Current post-loader live capture.' },
    profile: { composition: 'Place packaging in the lower center, crop a giant brand word across the top, and distribute short nutrition callouts around the product.', palette: 'multiple matcha greens, cream, white, and near black', texture: 'matte packaging with marker-like handwritten accents', motion: 'slide product pieces and callouts into place with buoyant timing', preserve: 'the controlled single-color world and product-first scale', avoid: 'smooth wellness gradients, ingredient photography, dense nutrition tables' },
  },
  {
    id: 'site-aside', order: 39, title: 'Aside Browser', styleDescriptor: 'Product world / cloud-soft interface',
    description: 'A browser interface floats in a blue-sky environment beneath an ambitious centered proposition, combining familiar UI with an optimistic illustrated atmosphere.',
    primaryCategory: 'Illustrated Storybook', extraFilters: ['Reference Styles'], tags: ['sky world', 'browser mockup', 'centered headline', 'soft clouds', 'product demo'],
    source: { kind: 'website', siteName: 'Aside', url: 'https://aside.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'aside', originalAsset: '/assets/site-captures/21-aside.png' },
    media: { poster: '/assets/posters/site-21.jpg', detailImage: '/assets/site-captures/21-aside.png', original: '/assets/site-captures/21-aside.png', motionNotes: 'Cloud and interface layers move at different depths while product states demonstrate the browser concept.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['hero hierarchy', 'product staging', 'atmospheric palette'], note: 'Current live capture.' },
    profile: { composition: 'Center a large proposition in open sky and float a detailed browser interface across the lower half with clouds framing its edges.', palette: 'sky blue, cloud white, soft grey, and small product-status colors', texture: 'soft atmospheric gradients around crisp product UI', motion: 'use slow cloud parallax and purposeful in-interface demonstrations', preserve: 'the optimistic scale and readable browser surface', avoid: 'unreadably tiny UI, excessive glass blur, generic AI sparkle effects' },
  },
  {
    id: 'site-jitter', order: 40, title: 'Made with Jitter', styleDescriptor: 'Motion showcase / editorial index',
    description: 'A restrained motion-gallery introduction uses a large editorial statement and a carefully framed featured animation strip rather than a conventional template grid.',
    primaryCategory: 'Reference Styles', extraFilters: ['Print-Tech Paper'], tags: ['motion gallery', 'editorial intro', 'featured strip', 'white canvas', 'micro filters'],
    source: { kind: 'website', siteName: 'Made with Jitter', url: 'https://madewithjitter.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'jitter', originalAsset: '/assets/site-captures/22-jitter.png' },
    media: { poster: '/assets/posters/site-22.jpg', detailImage: '/assets/site-captures/22-jitter.png', original: '/assets/site-captures/22-jitter.png', motionNotes: 'Featured work plays in curated loops while the surrounding gallery interface remains typographically calm.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['gallery framing', 'typography', 'motion hierarchy'], note: 'Current live capture.' },
    profile: { composition: 'Open with a centered editorial statement and place a wide featured-animation strip below a compact category filter.', palette: 'white, black, and colors supplied by the featured work only', texture: 'clean editorial canvas surrounding rich motion thumbnails', motion: 'allow curated loops inside bounded media while keeping the page shell still', preserve: 'the calm editorial wrapper and work-led color', avoid: 'autoplay everywhere, equal-weight thumbnail walls, decorative background motion' },
  },
  {
    id: 'site-pen', order: 41, title: 'Pen.dev', styleDescriptor: 'Design tool / typographic utility',
    description: 'A centered proposition—“Dream on canvas. Land in code.”—is surrounded by faint perspective lines and compact download controls.',
    primaryCategory: 'Print-Tech Paper', extraFilters: ['Reference Styles'], tags: ['centered proposition', 'perspective grid', 'design tool', 'mono controls', 'white canvas'],
    source: { kind: 'website', siteName: 'Pen.dev', url: 'https://www.pen.dev/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'pen', originalAsset: '/assets/site-captures/23-pen.png' },
    media: { poster: '/assets/posters/site-23.jpg', detailImage: '/assets/site-captures/23-pen.png', original: '/assets/site-captures/23-pen.png' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['hierarchy', 'typography', 'grid texture', 'conversion pattern'], note: 'Current live capture.' },
    profile: { composition: 'Center a two-line design-tool promise and two compact actions over a nearly invisible perspective construction grid.', palette: 'white, ink black, and faint cool grey', texture: 'fine drafting lines and minimal interface rules', motion: 'let construction lines shift subtly with pointer movement; keep text fixed', preserve: 'the memorable two-part promise and understated technical field', avoid: 'canvas screenshots above the fold, neon gradients, verbose feature copy' },
  },
  {
    id: 'site-coda', order: 42, title: 'Coda Commerce', styleDescriptor: 'Merchant platform / bold print campaign',
    description: 'A merchant-of-record campaign uses oversized stamped lettering, tiny orbit-like symbols, and a huge dark green arc to create a confident print-led first frame.',
    primaryCategory: 'Print-Tech Paper', extraFilters: ['Reference Styles'], tags: ['stamped wordmark', 'dark green arc', 'cream paper', 'merchant platform', 'campaign headline'],
    source: { kind: 'website', siteName: 'Coda', url: 'https://www.coda.co/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'coda', originalAsset: '/assets/site-captures/24-coda.png' },
    media: { poster: '/assets/posters/site-24.jpg', detailImage: '/assets/site-captures/24-coda.png', original: '/assets/site-captures/24-coda.png', motionNotes: 'Graphic symbols and the large geometric field shift with campaign-like transitions while conversion controls stay compact.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['type treatment', 'campaign composition', 'palette', 'brand tone'], note: 'Current live capture.' },
    profile: { composition: 'Center a stamped multi-word promise above a huge dark geometric arc and keep conversion actions small at the lower corners.', palette: 'warm cream, deep forest green, black, and pale yellow', texture: 'screen-printed lettering, tiny registration symbols, and flat paper color', motion: 'shift symbols and geometric fields in bold but infrequent campaign transitions', preserve: 'the print confidence and giant lower arc', avoid: 'payment-dashboard screenshots, glossy fintech gradients, oversized CTA pills' },
  },
  {
    id: 'site-izanami', order: 43, title: 'Izanami', styleDescriptor: 'Fashion philosophy / fog-bound landscape',
    description: 'A misty vertical landscape hides a small philosophical declaration, creating a meditative fashion entrance that rewards patience rather than immediate conversion.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Classical Remix'], tags: ['fog landscape', 'fashion entrance', 'tiny declaration', 'muted grey', 'slow reveal'],
    source: { kind: 'website', siteName: 'Izanami', url: 'https://izanami-official.com/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'izanami', originalAsset: '/assets/site-captures/25-izanami.png' },
    media: { poster: '/assets/posters/site-25.jpg', detailImage: '/assets/site-captures/25-izanami.png', original: '/assets/site-captures/25-izanami.png', motionNotes: 'A long loader gives way to an ambient fog scene and restrained philosophical text.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 0.94, reliableFor: ['atmosphere', 'scale', 'entrance pacing', 'palette'], note: 'Current atmospheric post-loader capture.' },
    profile: { composition: 'Fill the frame with a vertically layered fog landscape and place one tiny declaration near the center or lower third.', palette: 'mist grey, desaturated sage, charcoal, and pale stone', texture: 'soft film grain, fog layers, and barely visible terrain', motion: 'use a patient loader followed by continuous slow fog drift', preserve: 'the mystery, tiny type scale, and refusal of conventional conversion', avoid: 'large fashion headlines, visible product grids, dramatic fast transitions' },
  },
  {
    id: 'site-ctgt', order: 44, title: 'CTGT Frontier Intelligence', styleDescriptor: 'AI infrastructure / mountain-scale proof',
    description: 'A regulated-AI proposition sits over a dramatic mountain basin, using the landscape as a metaphor for frontier scale and disciplined navigation.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Data-as-Texture', 'Reference Styles'], tags: ['mountain hero', 'AI governance', 'editorial headline', 'dark overlay', 'edge controls'],
    source: { kind: 'website', siteName: 'CTGT', url: 'https://www.ctgt.ai/', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'ctgt', originalAsset: '/assets/site-captures/26-ctgt.png' },
    media: { poster: '/assets/posters/site-26.jpg', detailImage: '/assets/site-captures/26-ctgt.png', original: '/assets/site-captures/26-ctgt.png', motionNotes: 'The mountainous film and dark overlay create slow environmental depth behind stable product navigation.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['composition', 'landscape metaphor', 'headline scale', 'navigation'], note: 'Current live capture.' },
    profile: { composition: 'Place a large AI-governance proposition on the left over a full-bleed mountain basin and anchor small controls to the frame edges.', palette: 'charcoal, alpine green, fog white, and muted stone', texture: 'cinematic landscape photography with a deep translucent overlay', motion: 'use slow environmental film or parallax while interface controls remain fixed', preserve: 'the frontier metaphor and serious regulated-domain tone', avoid: 'robot imagery, abstract AI gradients, busy compliance diagrams in the hero' },
  },
  {
    id: 'site-ctgt-finance', order: 45, title: 'CTGT Finance', styleDescriptor: 'Industry narrative / governed ascent',
    description: 'The finance industry page sharpens the same mountain world with a governance statement and three compact capability panels along the bottom edge.',
    primaryCategory: 'Vast Quiet Cinematic', extraFilters: ['Data-as-Texture', 'Reference Styles'], tags: ['mountain ridge', 'governance headline', 'feature panels', 'dark green', 'industry page'],
    source: { kind: 'website', siteName: 'CTGT Finance', url: 'https://www.ctgt.ai/industries/finance', captureMethod: 'live-browser-capture', capturedAt: '2026-08-21', sourceGroupId: 'ctgt', originalAsset: '/assets/site-captures/27-ctgt-finance.png' },
    media: { poster: '/assets/posters/site-27.jpg', detailImage: '/assets/site-captures/27-ctgt-finance.png', original: '/assets/site-captures/27-ctgt-finance.png', motionNotes: 'Slow landscape motion supports a fixed governance message while the bottom feature panels behave as a measured navigation layer.' },
    quality: { tier: 'canonical', width: 1440, height: 900, confidence: 1, reliableFor: ['industry-page hierarchy', 'feature-panel integration', 'landscape staging'], note: 'Current live capture.' },
    profile: { composition: 'Overlay a concise governance statement on a sharp mountain ridge and dock three small capability panels across the lower edge.', palette: 'deep forest green, graphite, cloud white, and restrained grey', texture: 'cinematic terrain beneath precise translucent information panels', motion: 'keep a slow environmental film behind stable copy and measured panel transitions', preserve: 'the landscape continuity and integrated bottom capability rail', avoid: 'separate floating cards, finance stock imagery, bright dashboard charts' },
  },
];

export const references = ReferenceManifestSchema.parse(
  [...imageSeeds, ...siteSeeds].map(buildEntry),
);

export const categories: Array<'All' | Category> = [
  'All',
  'Print-Tech Paper',
  'Dither Mono',
  'Vast Quiet Cinematic',
  'Data-as-Texture',
  'Classical Remix',
  'Glitched Antiquity',
  'Illustrated Storybook',
  'Reference Styles',
];
